-- FreePoolLog4U Mini beta.4 – konfigurierbare Reinigungsarten pro Pool
create table if not exists public.pool_cleaning_types (
  id bigint generated by default as identity primary key,
  pool_id uuid not null references public.pools(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 60),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(pool_id, name)
);

alter table public.pool_cleaning_types enable row level security;

drop policy if exists "pool_cleaning_types_select_own" on public.pool_cleaning_types;
create policy "pool_cleaning_types_select_own" on public.pool_cleaning_types for select to authenticated
using (exists (select 1 from public.pools p where p.id=pool_id and p.owner_user_id=auth.uid()));

drop policy if exists "pool_cleaning_types_insert_own" on public.pool_cleaning_types;
create policy "pool_cleaning_types_insert_own" on public.pool_cleaning_types for insert to authenticated
with check (exists (select 1 from public.pools p where p.id=pool_id and p.owner_user_id=auth.uid()));

drop policy if exists "pool_cleaning_types_update_own" on public.pool_cleaning_types;
create policy "pool_cleaning_types_update_own" on public.pool_cleaning_types for update to authenticated
using (exists (select 1 from public.pools p where p.id=pool_id and p.owner_user_id=auth.uid()))
with check (exists (select 1 from public.pools p where p.id=pool_id and p.owner_user_id=auth.uid()));

drop policy if exists "pool_cleaning_types_delete_own" on public.pool_cleaning_types;
create policy "pool_cleaning_types_delete_own" on public.pool_cleaning_types for delete to authenticated
using (exists (select 1 from public.pools p where p.id=pool_id and p.owner_user_id=auth.uid()));
